### ISSUE TITLE
[Platform] Lens Distortion Correction Stream

### ISSUE THREAD

**Issue by oussamabonnor1** [evercam/ex_nvr#186]
### Description:
For cameras that do not offer LDC (Lens Distortion Correction), we need a way to undistort BIM images before they show up on the client side.

### Proposed Solution:
The idea is to use the [OpenCV Undistort](https://shimat.github.io/opencvsharp_docs/html/9b3d4b92-0fc2-dfec-e2e4-3bc64516047a.htm) function to fix the distortion effect before it reaches the client side (as a pre-render filter).

### An Alternative (For the future):
Including an undistortion filter or phase into the EX_NVR.

### The Compromise:
The BIM Compare will have a slightly different view that the Live View since the latter will have no LDC on.

@marcoherbst, @salah-walid will work on this now as a prototype and hopefully it'll be a quick and relatively easy fix for this issue.

**Comment by marcoherbst** [comment]
As of latest firmware updates we can now do this on all the cameras we work with. I think we should close this. can be come back to if it is ever needed again.

**Comment by oussamabonnor1** [comment]
@salah-walid the PR linked to this seems to have been closed. Can we link it to a PR that made it to prod to have an accurate history here?

**Comment by marcoherbst** [comment]
I think the point is that we no longer want or need this feature. We have LDC on the cameras and we're not likely to prioritise this feature. 

That's my rationale for closing the issue and I think Billal closed the PR because I close the issue.
