### ISSUE TITLE
UI: Snapshot Download (to browser)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/ex_nvr#215]
Seems an obvious one to have. Not urgent. To local browser downloads. Similar to Evercam.

**Comment by FerielKHA** [comment]
@marcoherbst do you mean by that to download a folder within the pictures ? 
For example, if I have a 1-minute video and capture snapshots every 10 seconds, would this result in downloading a folder containing 10 pictures?

**Comment by FerielKHA** [comment]
The snapshot to download is the one that is currently displayed when the user clicks the download button.

**Comment by gBillal** [comment]
@Mebareksaf see [this](https://github.com/video-dev/hls.js/issues/2011)
