### ISSUE TITLE
When I switch cameras, the date is not retained

### ISSUE THREAD

**Issue by FerielKHA** [evercam/ex_nvr#217]
When I switch cameras, the date is not retained.

<img width="630" alt="image" src="https://github.com/evercam/ex_nvr/assets/51049639/fc518a77-ea26-46d5-98cc-7b5a85890a48">

**Comment by FerielKHA** [comment]
@gBillal need updates here :) if it's done, close it please. We need to close V.05 milestone.

**Comment by marcoherbst** [comment]
It's not obvious to me that this is a needed feature or user intuitive. I'm closing it, billal is welcome to open it if he disagrees.
