### ISSUE TITLE
Remove or Delete a device

### ISSUE THREAD

**Issue by marcoherbst** [evercam/ex_nvr#241]
![image](https://github.com/evercam/ex_nvr/assets/5648894/3575c8c7-94b3-4569-9e0b-4992378b7a82)

I think there's a "Delete" option missing here.

**Comment by FerielKHA** [comment]
@marcoherbst in which section I'll find this ? 
What's the impact of this action ? If the device is used ? Is it irreversible ?

**Comment by marcoherbst** [comment]
Great question. 

My suggestion is that if we delete the camera, then the recordings are also deleted. Another approach would be some form of soft-delete or recycle bin, but for now, I would propose delete = delete.

I don't have absolute opinions on this, if someone wants to spec a more detailed answer, that's fine, especially if it references what other applications do.
