### ISSUE TITLE
Improve playback performance + Offer different resolutions

### ISSUE THREAD

**Issue by halimb** [evercam/ex_nvr#283]
The HLS playback performance is not optimal at the moment.

Here's an example on Evercam dashboard's HLS player:

![play](https://github.com/evercam/ex_nvr/assets/20999471/00b6737a-7364-4b56-a8ec-13a2e4a78ea5)

----------------

We should investigate and address the causes for these slowdowns.

One theory is offering smaller resolutions, although not sure it would fix it.

**Comment by marcoherbst** [comment]
@FerielKHA I think we could split this into 2 issues.

One of them is to **Add resolutions options for playback in the ExNVR UI**

One of them is Halim's **Improve Playback Performance** (the origional one).   This one may be solved by the first one, but not necessarily. I'd just like a more clear distinction between them.

**Comment by FerielKHA** [comment]
@halimb can we have a speed call about this please?

**Comment by halimb** [comment]
@FerielKHA sure, but I can already say this particular issue is outdated.
What happened since then:

1- We used different resolutions, but realized it's not the issue (also, changing resolutions may actually affect the performance negatively for the frontend as there's transcoding involved in ex_nvr)
2- Most of the perfomance concerns are network issues (at the camera level or VPN)

I suggest to close this for now, until more precise issues surface from https://github.com/evercam/evercam-frontend/issues/8371
