### ISSUE TITLE
Switch between light/dark modes

### ISSUE THREAD

**Issue by gBillal** [evercam/ex_nvr#30]

**Comment by FerielKHA** [comment]
It's a nice-to-have. Let's prioritize it for later, once we've completed essential user functionalities.

**Comment by Mebareksaf** [comment]
UPDATE:
@FerielKHA @gBillal @halimb 

Added a switch mode button, but light mode colors are needed since only white is not very appealing:

![Screenshot 2024-01-22 at 10 46 58 AM](https://github.com/evercam/ex_nvr/assets/30500856/7235ee26-4786-4054-bfd5-244ffd2efc85)
