### ISSUE TITLE
Ability to fix Camera time to have correct recording time.

### ISSUE THREAD

**Issue by magixus** [evercam/ex_nvr#34]
For hikvision, it's simple, 

1. Setup NTP
![image](https://github.com/evercam/ex_nvr/assets/7642058/c3c45941-cbb8-4337-b680-47404fbf2a27)

2. Setup timezone (same as jetson)
![image](https://github.com/evercam/ex_nvr/assets/7642058/8c0cde55-a13c-420e-98a3-f1f3ccf09a25)

3- REBOOT
![image](https://github.com/evercam/ex_nvr/assets/7642058/fbdbe528-c77c-45f9-b2c6-130c09347f70)

**Comment by FerielKHA** [comment]
@gBillal any updates here please ?

**Comment by marcoherbst** [comment]
https://github.com/evercam/ex_nvr/issues/369 moved here.
