### ISSUE TITLE
Storage Details

### ISSUE THREAD

**Issue by FerielKHA** [evercam/ex_nvr#356]
Goal:
Being able to view storage details here without having to log into the pi

Storage details such as:

1 - Quantity of drives
2 - Status of drives
3 - Capacity of drives / Free Space
4 - Type of storage
5 - Avg MB/Min

<img width="211" alt="image" src="https://github.com/evercam/ex_nvr/assets/51049639/9edd3c03-9a4c-4f3b-a819-b9bf12851461">

**Comment by halimb** [comment]
@gBillal @FerielKHA can we get the storage info exposed in the Rest API as well?

**Comment by marcoherbst** [comment]
This is similar to https://github.com/evercam/ex_nvr/issues/19 so I will close this and link to this one for reference.
