### ISSUE TITLE
Reboot and or Restart

### ISSUE THREAD

**Issue by FerielKHA** [evercam/ex_nvr#357]
Goal:
Being able to restart services and or pi/jetson without having to login via SSH
Either restart exnvr and related services
Or 
Reboot the Pi

**Comment by gBillal** [comment]
Context ?? why restarting ex_nvr ? why restarting the pi/jetson ??

**Comment by FerielKHA** [comment]
We'll check this later, since we currently have the possibility of reboot via SSH.

**Comment by marcoherbst** [comment]
I will add this as a minor function that could possibly be handled with livebook. Closing it here.
