### ISSUE TITLE
Calendar - ok or submit button 

### ISSUE THREAD

**Issue by FerielKHA** [evercam/ex_nvr#358]
Goal:
Being able to close the menu with a done button

<img width="355" alt="image" src="https://github.com/evercam/ex_nvr/assets/51049639/6c003403-52e5-495b-ae3f-9a686784e78a">

**Comment by gBillal** [comment]
As I said before to @marcoherbst there's no way to change the behavior of html5 calendar. A custom one is needed to add button.

**Comment by gBillal** [comment]
For reference https://github.com/evercam/ex_nvr/issues/258
