### ISSUE TITLE
Show available recordings on calendar

### ISSUE THREAD

**Issue by magixus** [evercam/ex_nvr#36]
A user would like to see whether recordings exist or not.  (to use for download for incident requests)

For example, Hikvision shows blue dots with timeline 
![image](https://github.com/evercam/ex_nvr/assets/7642058/6d8b639a-8726-4f75-ac9a-bee97ab9f43d)

NXW shows green days with timeline 
![image](https://github.com/evercam/ex_nvr/assets/7642058/4bb5bffc-144b-41d4-8636-c86feb0f3eb2)

@magixus I've rephrased this issue to focus on the functionality that we do want (ability to see available recordings calendar) rather than what is not needed. I think your main point is good.

**Comment by marcoherbst** [comment]
This was a nicely written issue, but i think the task is now handled by incorporating the timeline UI which also shows available recordings.
