### ISSUE TITLE
No error feedback when downloading footage of a duration more than 2h

### ISSUE THREAD

**Issue by FerielKHA** [evercam/ex_nvr#360]
Goal:
To have a clear indicator that download is going to be processed and a time estimation (if possible).

**Comment by gBillal** [comment]
???

**Comment by FerielKHA** [comment]
When we click on download a record, nothing indicates that is in progress. We would like to have a message here.

**Comment by gBillal** [comment]
There's a progress bar on the browser, why we should implement it ourselves ?

**Comment by FerielKHA** [comment]
Just retested with @gBillal , I've tried to download 4h recording nothing happens (the error is not displayed)

**Comment by FerielKHA** [comment]
@Mebareksaf a video that you asked explaining the issue 


https://github.com/evercam/ex_nvr/assets/51049639/1c5297cd-f0ea-45b1-80d4-4a96bff9c79a

**Comment by Mebareksaf** [comment]
> @Mebareksaf a video that you asked explaining the issue 
> 
> 
> https://github.com/evercam/ex_nvr/assets/51049639/1c5297cd-f0ea-45b1-80d4-4a96bff9c79a
> 
> 

@FerielKHA Thank you so much, that's much better

**Comment by Mebareksaf** [comment]
@gBillal i just noticed that this is a deployed ExNVR, does it use the version where we fixed the previous errors? (disconnected socket, end_date validation correction)

**Comment by Mebareksaf** [comment]
@FerielKHA @gBillal the V0.9.1 does not contain the latest changes and fixes

**Comment by gBillal** [comment]
@Mebareksaf @FerielKHA already fixed
