### ISSUE TITLE
Pause/Play Stream

### ISSUE THREAD

**Issue by FerielKHA** [evercam/ex_nvr#362]
Goal:
In cases where network connectivity is bad or limited, we should be able to pause the stream. Especially in cases where we are trying to preserve bandwidth and or improve download performance.
<img width="412" alt="image" src="https://github.com/evercam/ex_nvr/assets/51049639/b91241fb-4f34-4bf8-87a8-22b653e2c104">

+ add control boutons ( to specify)

**Comment by gBillal** [comment]
Just click on the player or on the `space bar` and the player will pause

**Comment by FerielKHA** [comment]
@wqas-evercam does it suits you ?

**Comment by marcoherbst** [comment]
Can live here: https://github.com/evercam/ex_nvr/issues/391 it seems to me that it would be more normal to have pause/play.
