### ISSUE TITLE
ExNVR recordings with Hanwha cameras

### ISSUE THREAD

**Issue by smaude87** [evercam/ex_nvr#407]
There is a recording issue on the Hanwha branded cameras where the recordings are not continuous.
![image](https://github.com/evercam/ex_nvr/assets/164302121/e73a103f-42fb-48bb-96ac-3c1153f01a55)

I have NX recording on the same server and there seems to be no interruptions in the continuous recordings.
![image](https://github.com/evercam/ex_nvr/assets/164302121/5fd5f2a7-06fd-4401-8ab4-cf745a3f01b8)

Camera ID: auhan-ilvuo

Camera model: Hanwha PNO-8091R

**Comment by gBillal** [comment]
Hi @smaude87 
Can you please try to free space on the device so we can disable the overwriting in the NVR. There's a bug there, so I cannot point the exact issue.
Either put this camera on a new device or delete old recordings from the hard drive

**Comment by gBillal** [comment]
it's recording for a few hours now (the bug is in the delete old recordings), I'll try different config and investigate the issue more
![image](https://github.com/evercam/ex_nvr/assets/84322223/506a4cd2-bcce-4c46-83f8-e458a6757233)

**Comment by smaude87** [comment]
@gBillal i had to return the camera today, we are shipping them to a Philippines project.  I have another camera on the way to keep the test rolling.  I suspect we will be using this brand of camera frequently in asia.

**Comment by gBillal** [comment]
great @smaude87, keep me updated when the new camera is online.
