### ISSUE TITLE
snapshots milisecond accuracy

### ISSUE THREAD

**Issue by Diaislam** [evercam/ex_nvr#428]
Description: 
the endpoint to request a snapshot from exnvr is not accurate with miliseconds 
camera exid newwa-dyrua
Example: 

image request newwa-dyrua_2024_04_19_10_58_05_400 , second: 5 , milisecond = 100
![Screenshot from 2024-05-10 12-45-39](https://github.com/evercam/ex_nvr/assets/33395350/258343c5-8539-4c22-afbb-a4d49a3ced74)
image request  newwa-dyrua_2024_04_19_10_58_05_700 second: 4 milisecond = 700 is the same exact image 
![image](https://github.com/evercam/ex_nvr/assets/33395350/12c8bbe1-f0aa-4fb0-af3a-6565f73b386b)

600 miliseconds difference but getting the same image

**Comment by gBillal** [comment]
Hi @Diaislam 
I tried with this camera I get the following results
`2024-04-19T10:58:05.000Z`
![image](https://github.com/evercam/ex_nvr/assets/84322223/917c67eb-7860-495b-a449-a0f75ad3e211)

`2024-04-19T10:58:05.500Z`
![image](https://github.com/evercam/ex_nvr/assets/84322223/8de2ba43-80fe-46c0-8231-97b46807848c)

The two images are not the same. Are you sure that you provide the right timestamps ?

**Comment by Diaislam** [comment]
![image](https://github.com/evercam/ex_nvr/assets/33395350/45745252-6d59-4ace-953e-fd502393159a)
yes correct but if you try the timestamps i sent milisecond 100 & milisecond 700 they are the same image ,
the 

if you try  2024-04-19T10:58:04.500 and 2024-04-19T10:58:05.000 they are also the same image, what i'm trying to say is in one second there are only 2 images mostly

**Comment by gBillal** [comment]
Nope they're not the same, I tried with 100 millisecond and 300 millisecond and it gave me different images
