### ISSUE TITLE
EXNVR HTTPS Port Closes on RPi5 frequently

### ISSUE THREAD

**Issue by dhairyas17** [evercam/ex_nvr#477]
We have noticed a couple of times that after some time of running, the exnvr HTTPS port closes by itself without giving any error in the log, making it unreachable. This issue is primarily observed on the Raspberry Pi 5 and might be related to firmware (may be). 

It significantly affects gate report cameras, as the NVRs become unreachable through the HTTPS port while processing ANPR events.

Restarting the EXNVR service on the Pi temporarily fixes the issue, but it reoccurs periodically

**Comment by marcoherbst** [comment]
We discussed a server side scripted workaround (if port closed, restart service). Of course this script could also run locally. If needed by checking port open state using somthing like https://canyouseeme.org/
