### ISSUE TITLE
Timeline cleanup

### ISSUE THREAD

**Issue by marcoherbst** [evercam/ex_nvr#77]
I dont think it makes sense to show Mon Tue Wed (the days of the week)

![image](https://github.com/evercam/ex_nvr/assets/5648894/3de5718f-bbec-4fcd-911c-ab1b0c2c6523)

or the time when it's 00:00:00 

![image](https://github.com/evercam/ex_nvr/assets/5648894/8db5f0bf-6a41-473f-8e07-b665ff95236f)

**Comment by marcoherbst** [comment]
@gBillal did we lose screenshots when we went public?

**Comment by gBillal** [comment]
Yes, all uploaded assets to issues and PRs will be lost unless you go private ago (I think it's kind of a security measure by github)

**Comment by marcoherbst** [comment]
Closing this issue, it was small UI stuff and without the screenshots it's silly.
